version: "3.8"

services:
  php-apache:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - postgres
    environment:
      POSTGRES_DB: your_db
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
    volumes:
      - ./src:/var/www/html

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: postgrees
      POSTGRES_USER: postgrees
      POSTGRES_PASSWORD: postgrees
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
