version: "3.8"

services:
  php-apache:
    build: .
    container_name: php_app
    ports:
      - "80:80"
    depends_on:
      - postgres
    volumes:
      - ./src:/var/www/html
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: postgres
      POSTGRES_HOST: postgres
    command: apache2-foreground

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
